ARG img_version=4.2
FROM godot-fedora-base:${img_version}

ENV EMSCRIPTEN_VERSION=3.1.64

RUN git clone --branch ${EMSCRIPTEN_VERSION} --progress https://github.com/emscripten-core/emsdk && \
    emsdk/emsdk install ${EMSCRIPTEN_VERSION} && \
    emsdk/emsdk activate ${EMSCRIPTEN_VERSION}

CMD /bin/bash -c "source /root/emsdk/emsdk_env.sh && /bin/bash"
